# アプリケーションを動かすための要素
services:
  django-sns-app:
    # 利用するイメージを指定
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18-bullseye
    init: true
    # ホストのポート番号とコンテナーのポート番号のマッピング(対応付け)を定義([Host Port]:[Container Port])
    ports:
      - '3000:8080'
    # 起動時のコマンドを指定
    command: /bin/sh -c "chown -R $UID:$GID /home/node/workspace/node_modules; while sleep 1000; do :; done"
    # 外部ホストのIPアドレスを指定
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # マウントする設定ファイルのパスを指定(ローカル:コンテナ)
    volumes:
      - ..:/home/node/workspace:cached
      - ~/.ssh:/home/node/.ssh
      - node-modules:/home/node/workspace/node_modules
    # 作業ディレクトリを指定
    working_dir: /home/node/workspace

volumes:
  node-modules:
